version: '2'
services:
    flightstask-app:
        image: flightstask
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://flightstask-mysql:3306/flightstask?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flightstask-mysql:
        extends:
            file: mysql.yml
            service: flightstask-mysql
